### ISSUE TITLE
app.js not found on Windows

### ISSUE THREAD

**Issue by AurelioDeRosa** [krasimir/react-webpack-starter#10]
Hi.

I've cloned the repository and installed all the dependencies. Then, I ran `npm run dev` and accessed the URL, but the `app.js` file is not found. I'm not sure this is a platform specific problem, but I'm on Windows 10.

**Comment by krasimir** [comment]
It's not only you. I was able to reproduce the problem under Mac. It's fixed now. Thank you for spotting this.
