### ISSUE TITLE
error on build: "Definition for rule 'keyboard-spacing' was not found

### ISSUE THREAD

**Issue by ueeieiie** [krasimir/react-webpack-starter#14]
Hey, I just cloned the repo and tried to run it for the first time.
I installed it as mantioned, it when i ran 'npm run build' I got this error:

> 1:1  error  Definition for rule 'keyword-spacing' was not found  keyword-spacing

do you know what is causing it ?

**Comment by krasimir** [comment]
Yep, fixed now. Sorry `eslint` was an really old version. Just published `1.0.0` version of this package which is working.
