### ISSUE TITLE
would a project built using this kit, work on Github pages?

### ISSUE THREAD

**Issue by Neats29** [krasimir/react-webpack-starter#3]
Thanks for building this great starter kit. I've made a project with it and have pushed to github pages but the app.js in index.html comes back with a 404. Just wanted to know if you know if a project built with this would work on Github pages. Thanks.

**Comment by krasimir** [comment]
Yep, it should work since it's only HTML, JavaScript and CSS. Is it possible to show me a url to your repository?

You may check the path to the `app.js` file.

**Comment by Neats29** [comment]
this is the repo: https://github.com/Neats29/React-Unit-Converter
and the g pages url: http://neats29.github.io/React-Unit-Converter/pub/index.html
app.js works in localhost so I'm assuming the path is correct.

**Comment by krasimir** [comment]
I think you should change
```html
<script src="app.js"></script>
```
to
```
<script src="../lib/app.js"></script>
```

**Comment by Neats29** [comment]
I tried that before in localhost and it didn't work but maybe it's different when it's being served on g pages?

**Comment by krasimir** [comment]
Well ... http://neats29.github.io/React-Unit-Converter/lib/app.js exists

**Comment by Neats29** [comment]
It worked, thanks. Do you know why the path to app.js that works in localhost is different to that on gh-pages?

**Comment by krasimir** [comment]
Hm .. this sounds weird. Should work the same way on your localhost.

**Comment by Neats29** [comment]
That's why I thought maybe this was a gh-pages issue because in localhost only ```<script src="app.js"> </script>``` works, and in live ```<script src="../lib/app.js"></script>``` works. Well thanks anyway, I will look into it.

**Comment by krasimir** [comment]
:+1:
