### ISSUE TITLE
Illegal import declaration

### ISSUE THREAD

**Issue by wklc2015** [krasimir/react-webpack-starter#4]
hello, I have install all npm package, when I run "npm run dev",  There is an error "Illegal import declaration", Do you know how resolve this error?

And I have run with chrome browser, The error is "import React from 'react';";

Is the error ES6 grammar I use?

**Comment by krasimir** [comment]
Hello,

How is your `import` statement looks like?

**Comment by krasimir** [comment]
@wklc2015 dod you manage to solve your problem?

**Comment by krasimir** [comment]
@wklc2015 I'll close this issue. Open it if you still have this issue.
